// Bullshit Bingo Word Lists
const WORD_LISTS = {
  cybersecurity: {
    name: "Cybersecurity",
    icon: "🔐",
    words: [
      "Zero Trust",
      "AI-Powered Threat Detection",
      "Next-Gen Firewall",
      "Cyber Resilience",
      "Attack Surface",
      "Threat Actor",
      "Lateral Movement",
      "Defense in Depth",
      "Security Posture",
      "Advanced Persistent Threat",
      "Ransomware-as-a-Service",
      "Shift Left Security",
      "Cyber Hygiene",
      "Zero-Day Exploit",
      "Threat Intelligence",
      "Kill Chain",
      "Penetration Testing",
      "Red Team / Blue Team",
      "SOC 2 Compliance",
      "Endpoint Detection",
      "SIEM Solution",
      "Threat Landscape",
      "Cyber Kill Chain",
      "Nation-State Actor",
      "Breach Prevention",
      "Security-First Culture",
      "Passwordless Authentication",
      "Least Privilege",
      "Supply Chain Attack",
      "Insider Threat",
      "Crypto-Agility",
      "XDR Platform",
      "SOAR Automation",
      "Cloud-Native Security",
      "DevSecOps"
    ]
  },
  
  iot: {
    name: "Internet of Things",
    icon: "📡",
    words: [
      "Smart Everything",
      "Edge Computing",
      "Digital Twin",
      "Connected Ecosystem",
      "Sensor Fusion",
      "Mesh Network",
      "Industrial IoT",
      "Smart City",
      "Predictive Maintenance",
      "Real-Time Analytics",
      "M2M Communication",
      "Embedded Systems",
      "Low-Power Wide-Area",
      "MQTT Protocol",
      "Device Orchestration",
      "IoT Gateway",
      "Fog Computing",
      "Smart Grid",
      "Wearable Technology",
      "Asset Tracking",
      "Remote Monitoring",
      "Connected Vehicle",
      "Smart Home Hub",
      "LoRaWAN",
      "5G-Enabled IoT",
      "Autonomous Systems",
      "Sensor Networks",
      "Over-the-Air Updates",
      "Device Lifecycle",
      "Interoperability",
      "Smart Manufacturing",
      "Connected Health",
      "Environmental Sensing",
      "Fleet Management",
      "Smart Agriculture"
    ]
  },
  
  ai: {
    name: "AI / Machine Learning",
    icon: "🤖",
    words: [
      "Deep Learning",
      "Neural Networks",
      "Artificial General Intelligence",
      "Machine Learning Ops",
      "Data is the New Oil",
      "Algorithmic Bias",
      "Model Training",
      "GPT-Powered",
      "Transformative AI",
      "Large Language Model",
      "Responsible AI",
      "AI Democratization",
      "Generative AI",
      "Prompt Engineering",
      "Foundation Models",
      "AI Alignment",
      "Multimodal AI",
      "RAG Architecture",
      "Fine-Tuning",
      "AI-First Strategy",
      "Inference at Scale",
      "AI Copilot",
      "Agentic AI",
      "Emergent Behavior",
      "AI Governance",
      "Vector Database",
      "Context Window",
      "Hallucination Problem",
      "Synthetic Data",
      "Reinforcement Learning",
      "AI Safety",
      "Ethical AI",
      "Cognitive Computing",
      "Natural Language Processing",
      "Computer Vision"
    ]
  },
  
  blockchain: {
    name: "Blockchain / Crypto",
    icon: "⛓️",
    words: [
      "Web3",
      "Decentralized",
      "Smart Contracts",
      "DeFi",
      "NFT Utility",
      "Tokenomics",
      "HODL",
      "To The Moon",
      "Layer 2 Solution",
      "Proof of Stake",
      "Gas Fees",
      "DAO Governance",
      "Yield Farming",
      "Liquidity Pool",
      "Trustless System",
      "On-Chain",
      "Metaverse",
      "Token Burn",
      "Whitepaper",
      "Airdrop",
      "Staking Rewards",
      "Cross-Chain Bridge",
      "dApp",
      "Cold Wallet",
      "Hash Rate",
      "Consensus Mechanism",
      "Fork",
      "Whale",
      "WAGMI",
      "Floor Price",
      "Mint",
      "Rugpull",
      "Diamond Hands",
      "Crypto Winter",
      "Self-Custody"
    ]
  },
  
  agile: {
    name: "Agile / Scrum",
    icon: "🏃",
    words: [
      "Sprint",
      "Backlog Grooming",
      "Story Points",
      "Velocity",
      "Retrospective",
      "Stand-Up Meeting",
      "Scrum Master",
      "Product Owner",
      "User Stories",
      "Kanban Board",
      "Burndown Chart",
      "Technical Debt",
      "Definition of Done",
      "Epic",
      "Spike",
      "Cross-Functional Team",
      "Continuous Improvement",
      "Fail Fast",
      "Iterate",
      "MVP",
      "Time-Boxing",
      "Blocker",
      "Ceremonies",
      "Planning Poker",
      "Release Train",
      "SAFe Framework",
      "Agile Transformation",
      "Self-Organizing Team",
      "Sprint Demo",
      "Acceptance Criteria",
      "WIP Limit",
      "Lead Time",
      "Cycle Time",
      "Value Stream",
      "Agile Mindset"
    ]
  },
  
  marketing: {
    name: "Marketing / Sales",
    icon: "📈",
    words: [
      "Growth Hacking",
      "Customer Journey",
      "Omnichannel",
      "Brand Awareness",
      "Lead Nurturing",
      "Conversion Funnel",
      "ABM Strategy",
      "Content is King",
      "Thought Leadership",
      "Influencer Marketing",
      "Viral Potential",
      "Engagement Metrics",
      "ROI-Driven",
      "Customer-Centric",
      "Value Proposition",
      "Go-To-Market",
      "Product-Market Fit",
      "Demand Generation",
      "Sales Enablement",
      "Pipeline Velocity",
      "Buying Signals",
      "Intent Data",
      "Personalization at Scale",
      "Attribution Model",
      "Customer Lifetime Value",
      "Upsell / Cross-Sell",
      "Net Promoter Score",
      "Brand Equity",
      "Market Penetration",
      "Competitive Differentiation",
      "Buyer Persona",
      "Pain Points",
      "Low-Hanging Fruit",
      "Quick Wins",
      "360-Degree View"
    ]
  },
  
  corporate: {
    name: "Corporate Speak",
    icon: "👔",
    words: [
      "Circle Back",
      "Synergy",
      "Move the Needle",
      "Low-Hanging Fruit",
      "Think Outside the Box",
      "Bandwidth",
      "Deep Dive",
      "Take Offline",
      "Leverage",
      "Value-Add",
      "Best Practices",
      "Win-Win",
      "Stakeholder Alignment",
      "Core Competency",
      "Action Items",
      "Going Forward",
      "At the End of the Day",
      "Touch Base",
      "Drill Down",
      "Boil the Ocean",
      "Run It Up the Flagpole",
      "Paradigm Shift",
      "Open the Kimono",
      "Bleeding Edge",
      "Game Changer",
      "Pivot",
      "Scalable Solution",
      "Ecosystem",
      "Holistic Approach",
      "Mission Critical",
      "Results-Driven",
      "Proactive",
      "Empower",
      "Streamline",
      "Optimize"
    ]
  },
  
  startup: {
    name: "Startup Culture",
    icon: "🚀",
    words: [
      "Disruptive Innovation",
      "Unicorn",
      "Series A/B/C",
      "Hockey Stick Growth",
      "Product-Market Fit",
      "Runway",
      "Burn Rate",
      "Pivot",
      "Scale Fast",
      "10x Engineer",
      "Hustle Culture",
      "Move Fast Break Things",
      "Venture-Backed",
      "Exit Strategy",
      "Bootstrapped",
      "Growth Mindset",
      "Iterate Quickly",
      "Lean Startup",
      "First-Mover Advantage",
      "Network Effects",
      "Moonshot",
      "Stealth Mode",
      "Soft Launch",
      "Traction",
      "CAC/LTV Ratio",
      "Freemium Model",
      "Virality",
      "Hypergrowth",
      "Blitzscaling",
      "Cap Table",
      "Term Sheet",
      "Due Diligence",
      "Pitch Deck",
      "Demo Day",
      "Founder-Led"
    ]
  },
  
  cloud: {
    name: "Cloud Computing",
    icon: "☁️",
    words: [
      "Multi-Cloud Strategy",
      "Cloud-Native",
      "Serverless",
      "Containerization",
      "Kubernetes",
      "Microservices",
      "Infrastructure as Code",
      "DevOps Pipeline",
      "CI/CD",
      "Auto-Scaling",
      "High Availability",
      "Disaster Recovery",
      "Cloud Migration",
      "Lift and Shift",
      "Hybrid Cloud",
      "Edge Computing",
      "API Gateway",
      "Service Mesh",
      "Observability",
      "Cloud-First",
      "Platform Engineering",
      "GitOps",
      "Immutable Infrastructure",
      "Blue-Green Deployment",
      "Canary Release",
      "SLA/SLO/SLI",
      "FinOps",
      "Cost Optimization",
      "Cloud Elasticity",
      "Managed Services",
      "Data Lake",
      "Event-Driven Architecture",
      "Vendor Lock-In",
      "Cloud Governance",
      "Zero Downtime"
    ]
  },
  
  datascience: {
    name: "Data Science",
    icon: "📊",
    words: [
      "Big Data",
      "Data Pipeline",
      "ETL Process",
      "Data Warehouse",
      "Feature Engineering",
      "A/B Testing",
      "Statistical Significance",
      "Predictive Analytics",
      "Data Democratization",
      "Self-Service BI",
      "Data Mesh",
      "Data Fabric",
      "Real-Time Analytics",
      "Data Lineage",
      "Data Governance",
      "Master Data Management",
      "Data Quality",
      "Batch Processing",
      "Stream Processing",
      "Data Catalog",
      "Metadata Management",
      "Data Observability",
      "Lakehouse Architecture",
      "dbt Transformation",
      "Semantic Layer",
      "Metrics Store",
      "Reverse ETL",
      "Data Contracts",
      "Schema Evolution",
      "Data Products",
      "Analytics Engineering",
      "Dimensional Modeling",
      "Time Series Analysis",
      "Cohort Analysis",
      "Funnel Analysis"
    ]
  }
};

// Export for use in app.js
if (typeof module !== 'undefined' && module.exports) {
  module.exports = WORD_LISTS;
}
